Profile creation pages: layout/validation/translation improvements
nemgrouplimited/symbol-desktop-wallet pull request #1078
Opened 2021-02-08 21:33 UTC by myxmaster

- Harmonized button styles
- Improved checkbox style
- Improved terms and conditions checkbox text
- Improved mnemonic input validation (show error even if first word is wrong)
- Removed unused translation and notification types
- Minor layout improvements

![grafik](https://user-images.githubusercontent.com/77545287/107276870-f3337e00-6a53-11eb-9f6d-eda30c61a444.png)

2021-02-11 09:32 UTC, rg911 requested changes
Please resolve conflict 
👍

2021-02-11 09:32 UTC, rg911 commented on src/language/zh-CN.json
> +    "mnemonic_correct": "记忆法是正确的",
"mnemonic_correct": "记忆法是正确的" => "mnemonic_correct": "助记词正确"

2021-02-12 19:08 UTC, myxmaster commented on src/language/zh-CN.json
> +    "mnemonic_correct": "记忆法是正确的",
done

2021-02-12 19:08 UTC, myxmaster commented
conflicts resolved

2021-02-12 19:10 UTC, rg911 approved these changes

2021-02-15 15:18 UTC, merged