Fixed hardcode translation
nemgrouplimited/symbol-desktop-wallet pull request #1177
Opened 2021-02-19 12:12 UTC by OlegLialin

Fixed hardcode translation

2021-02-19 12:14 UTC, segfaultxavi requested changes

2021-02-19 12:14 UTC, segfaultxavi commented on src/language/en-US.json
> +    "low_fee_warning_message": "Transaction with a less than recommended fee might not get accepted and eventually expire",
```suggestion
    "low_fee_warning_message": "Transactions with less than the recommended fee might not get accepted and eventually expire",
```

2021-02-19 14:13 UTC, rg911 approved these changes

2021-02-19 17:12 UTC, OlegMakarenko approved these changes

2021-02-19 17:19 UTC, OlegMakarenko commented
@OlegLialin Japanese and Chinese are machine translations, right?

2021-02-19 20:30 UTC, merged

2021-02-20 00:04 UTC, OlegLialin commented
@OlegMakarenko yes, it's Japanese and Chinese are machine translations