Issues fixes
nemgrouplimited/symbol-desktop-wallet pull request #1189
Opened 2021-02-21 13:47 UTC by bassemmagdy

2021-02-22 21:42 UTC, rg911 requested changes

2021-02-22 21:42 UTC, rg911 commented on src/language/zh-CN.json
> +    "action_label_alias_link": "Link Alias",
action_label_alias_link： 绑定别名
action_label_alias_unlink： 解绑别名

2021-03-01 18:56 UTC, yilmazbahadir approved these changes

2021-03-02 09:58 UTC, rg911 submitted a review, later dismissed

2021-03-02 09:59 UTC, rg911 approved these changes

2021-03-02 10:03 UTC, merged