Fixed translations
nemgrouplimited/symbol-desktop-wallet pull request #1198
Opened 2021-02-22 19:40 UTC by myxmaster

Fixed "directions" to backup profile button.

Japanese needs to be reviewed, Chinese needs to be updated.

2021-02-22 21:56 UTC, rg911 requested changes

2021-02-22 21:56 UTC, rg911 commented on src/language/en-US.json
> +    "if_you_need_to_back_up_your_mnemonics_again_you_can": "If you need to back up your mnemonics again, you can find them in 'Accounts - My Accounts - Back up Profile'.",
back up -> backup (in one word)

Chinese:
如果您需要再次备份助记词，请在“账户 - 我的账户 - 备份个人资料”页面操作。

2021-02-26 23:04 UTC, myxmaster commented on src/language/en-US.json
> +    "if_you_need_to_back_up_your_mnemonics_again_you_can": "If you need to back up your mnemonics again, you can find them in 'Accounts - My Accounts - Back up Profile'.",
done

2021-03-01 17:31 UTC, bassemmagdy approved these changes

2021-03-07 17:39 UTC, rg911 approved these changes

2021-03-07 17:39 UTC, merged