Message with 1024 characters not possible
nemgrouplimited/symbol-desktop-wallet pull request #1210
Opened 2021-02-24 16:49 UTC by james-lin71

2021-02-25 10:51 UTC, rg911 requested changes

2021-02-25 10:51 UTC, rg911 commented on src/core/validation/validators/MaxMessageValidator.ts
> +        return bytes < maxMessageNumber;
this is not quite right,  there is 1 byte (message type) appended to the message, so it will be 1 byte less

2021-03-05 16:25 UTC, bassemmagdy approved these changes

2021-03-05 16:37 UTC, rg911 approved these changes

2021-03-05 16:38 UTC, merged