fix #1076 #1416
nemgrouplimited/symbol-desktop-wallet pull request #1449
Opened 2021-04-20 08:50 UTC by bassemmagdy

2021-04-20 09:48 UTC, segfaultxavi requested changes

2021-04-20 09:48 UTC, segfaultxavi commented on src/language/en-US.json
> +    "login_to_symbol_account": "Login to your Symbol profile",
```suggestion
    "login_to_symbol_account": "Log in to your Symbol profile",
```

Maybe now is a good time to start fixing this mistake: "Log in" is a verb, whereas "login" is a noun:
https://english.stackexchange.com/questions/5302/log-in-to-or-log-into-or-login-to

2021-04-20 20:36 UTC, OlegMakarenko submitted a review, later dismissed

2021-06-07 14:46 UTC, AnthonyLaw approved these changes

2021-06-14 12:08 UTC, merged