Gh1090 improve transaction previews
nemgrouplimited/symbol-desktop-wallet pull request #1505
Opened 2021-05-27 15:27 UTC by bassemmagdy

fixes #1090

2021-05-28 06:18 UTC, OlegMakarenko commented
@bassemmagdy could you please provide a screenshot?

2021-05-28 08:24 UTC, segfaultxavi requested changes

2021-05-28 08:24 UTC, segfaultxavi commented on src/language/en-US.json
> +    "view_message": "view message"
```suggestion
    "view_message": "View message"
```

2021-06-10 08:11 UTC, rg911 approved these changes

2021-06-15 11:57 UTC, AdriaCarrera approved these changes

2021-06-16 07:56 UTC, merged