Bugfix/reset transfer tx form
nemgrouplimited/symbol-desktop-wallet pull request #556
Opened 2020-10-11 16:03 UTC by bassemmagdy

fixes #438

2020-10-14 11:01 UTC, yilmazbahadir approved these changes

2020-10-15 18:41 UTC, rg911 requested changes

2020-10-15 18:41 UTC, rg911 commented on src/views/forms/FormTransferTransaction/FormTransferTransactionTs.ts
> +    if (this.isMultisigMode()) this.resetForm()
should consider using curly bracket for better coding standard

2020-10-16 09:28 UTC, rg911 approved these changes

2020-10-16 09:37 UTC, merged