remove duplicated word definitions
nemgrouplimited/symbol-desktop-wallet pull request #636
Opened 2020-11-08 09:39 UTC by 44uk

2020-11-08 18:50 UTC, rg911 requested changes
Hi @44uk We are using the integration branch for now for all PRs, could you rebase the integration to yours, please?

2020-11-09 00:43 UTC, 44uk commented
> Hi @44uk We are using the integration branch for now for all PRs, could you rebase the integration to yours, please?

Create new branch from `integration`.

2020-11-09 09:22 UTC, rg911 approved these changes

2020-11-11 01:06 UTC, 44uk commented
It is already resolved.

2020-11-11 01:06 UTC, closed without merging