Dev metadata integration
nemgrouplimited/symbol-desktop-wallet pull request #640
Opened 2020-11-09 15:41 UTC by james-lin71

integration of creating metadata transaction
adding display component for the metadata transactions

2020-11-09 15:55 UTC, segfaultxavi requested changes
Minor grammar

2020-11-09 15:55 UTC, segfaultxavi commented on src/language/en-US.json
> +    "form_label_value_hint": "The value linked to an identifier is a string up to 1024 characters",
```suggestion
    "form_label_value_hint": "The value linked to an identifier is a string up to 1024 characters long",
```

2020-11-09 16:09 UTC, rg911 requested changes
metadata transaction is not working. 

Previous metadata value is not provided. 
Please use https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/dev/src/service/MetadataTransactionService.ts to create the metadata transaction

2020-11-16 15:14 UTC, rg911 approved these changes

2020-11-16 15:20 UTC, merged