click outside directive added, filter dropdown closing fixed
nemgrouplimited/symbol-desktop-wallet pull request #820
Opened 2020-12-14 16:00 UTC by NikolaiYurchenko

2020-12-16 11:14 UTC, rg911 requested changes

2020-12-16 11:14 UTC, rg911 commented on src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilterTs.ts
> +        console.log('1');
remove logs

2020-12-16 11:39 UTC, NikolaiYurchenko commented on src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilterTs.ts
> +        console.log('1');
done

2020-12-16 11:41 UTC, bassemmagdy approved these changes

2020-12-23 11:19 UTC, rg911 approved these changes

2020-12-23 12:13 UTC, merged