Added backup warning after PK account import
nemgrouplimited/symbol-desktop-wallet pull request #978
Opened 2021-01-27 20:41 UTC by OlegMakarenko

Resolved: #948
![image](https://user-images.githubusercontent.com/33131259/106051079-a44f2580-60f0-11eb-9d68-f806bba71003.png)

2021-01-27 20:56 UTC, rg911 requested changes
Nice one, 👍   could you add language files for Japanese and others?

2021-01-27 21:05 UTC, OlegMakarenko commented
> Nice one, 👍 could you add language files for Japanese and others?

@rg911 
What placeholder for values should I use, just to copy English?

2021-01-27 21:14 UTC, rg911 commented
> > Nice one, 👍 could you add language files for Japanese and others?
> 
> @rg911
> Sure. What placeholder for values should I use, just to copy English?

For the PR review, you can use translation software (e.g. google) for now

2021-01-27 21:48 UTC, cryptoBeliever commented
> > > Nice one, +1 could you add language files for Japanese and others?
> > 
> > 
> > @rg911
> > Sure. What placeholder for values should I use, just to copy English?
> 
> For the PR review, you can use translation software (e.g. google) for now, placeHolder should be the same for all languages,

@rg911 how you after that find messages to translate? Isn't better to use English (easier to find not translated messages)?

2021-01-27 21:56 UTC, OlegMakarenko commented
> > > > Nice one, +1 could you add language files for Japanese and others?
> > > 
> > > 
> > > @rg911
> > > Sure. What placeholder for values should I use, just to copy English?
> > 
> > 
> > For the PR review, you can use translation software (e.g. google) for now, placeHolder should be the same for all languages,
> 
> @rg911 how you after that find messages to translate? Isn't better to use English (easier to find not translated messages)?

@rg911 @cryptoBeliever I would suggest to add some set of chars to determine which translation is mock. Let say `>>` in the beginning

2021-01-28 07:34 UTC, segfaultxavi requested changes

2021-01-28 07:34 UTC, segfaultxavi commented on src/language/en-US.json
> +    "button_understand_title": "Understand",
```suggestion
    "button_understand_title": "Understood",
```

2021-01-28 07:34 UTC, segfaultxavi commented on src/language/en-US.json
> +    "modal_backup_reminder_content": "Please note that the Private Key account cannot be restored from your mnemonic passphrase. Please backup your profile again after import is complete to include t
```suggestion
    "modal_backup_reminder_content": "Please note that the Private Key account cannot be restored from your mnemonic passphrase. Backup your profile again after import is complete to include this account in the Paper Wallet.",
```

2021-01-28 10:33 UTC, OlegMakarenko commented on src/language/en-US.json
> +    "button_understand_title": "Understand",
Thank you 👍

2021-01-29 21:38 UTC, bassemmagdy approved these changes

2021-01-30 14:09 UTC, rg911 approved these changes

2021-01-31 14:09 UTC, merged