Multisig creation. Cosignatory account check
nemgrouplimited/symbol-desktop-wallet pull request #994
Opened 2021-01-29 11:04 UTC by OlegMakarenko

Resolved: #941

-Added check wether multisig cosignatory account is valid.
-Added error message for the account which is unknown to the network.

2021-01-31 11:39 UTC, rg911 requested changes

2021-02-02 12:16 UTC, bassemmagdy approved these changes

2021-02-02 13:06 UTC, rg911 approved these changes

2021-02-02 13:06 UTC, merged

2021-02-02 21:59 UTC, cryptoBeliever commented
I gave comment to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/941. PR moving to done.